codecov:
  notify:
    require_ci_to_pass: yes
  token: 4b04fe24-859f-4878-b873-e3a781f0399b

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: header, diff
  branches: *
  behavior: default
  require_changes: no

