language: php

dist: trusty

php:
  - 7.1
  - 7.2

sudo: false

matrix:
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

before_install:

  - phpenv config-rm xdebug.ini || true

  # initialize databases
  - mysql -u root -e "CREATE DATABASE homestead;"
  - mysql -u root -e "CREATE USER 'homestead'@'%' IDENTIFIED BY 'secret';";
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'homestead'@'%' WITH GRANT OPTION;"

install:

  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - cp .env.example .env
  - mkdir -p build/logs

  # show some versions and env information
  - php --version
  - composer --version

  - php artisan migrate --env=local --no-interaction -vvv
  - php artisan db:seed --env=local --no-interaction -vvv
  - php artisan migrate:rollback --env=local --no-interaction -vvv

script:
  - composer require php-coveralls/php-coveralls
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email: false
