language: php

dist: trusty

php:
  - 7.1
  - 7.2

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

notifications:
  email: false
