language: php

dist: trusty

php:
  - 7.1
  - 7.2

sudo: false

matrix:
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - mv .env.example .env
  - chmod -R 777 app/storage
  - mkdir -p build/logs
  - travis_retry composer install --no-interaction --prefer-source

install:
  - php artisan migrate --no-interaction -vvv
  - php artisan migrate:rollback --no-interaction -vvv

script:
  - composer require php-coveralls/php-coveralls
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v

notifications:
  email: false
