language: php

dist: trusty

php:
  - 7.1
  - 7.2

sudo: false

services:
  - mysql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - mysql -u root -e 'CREATE DATABASE homestead;'

install: travis_retry composer install --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

notifications:
  email: false
