language: php

dist: trusty

php:
  - 7.1
  - 7.2

sudo: false

matrix:
  fast_finish: true

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

services:
  - mysql

before_install:
  - mysql -u root -e "CREATE DATABASE IF NOT EXISTS 'homestead';"
  - mysql -u root -e "CREATE USER 'homestead'@'%' IDENTIFIED BY 'secret';";
  - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'homestead'@'%' WITH GRANT OPTION;"

install:
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - cp .env.example .env
  - mkdir -p build/logs
  - php artisan migrate --env=local --no-interaction -vvv
  - php artisan db:seed --env=local --no-interaction -vvv
  - php artisan migrate:rollback --env=local --no-interaction -vvv

script:
  - composer require php-coveralls/php-coveralls
  - php vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - travis_retry php vendor/bin/coveralls -v

notifications:
  email: false
